### ISSUE TITLE
got error node server.js

### ISSUE THREAD

**Issue by sipgear** [LordEidi/fennel#10]
fennel# node server.js
[2016-03-09 00:40:38.565] [DEBUG] fennelapp - logger loaded
/home/sbitdept/fennel/node_modules/libxmljs/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/sbitdept/fennel/node_modules/libxmljs/build/xmljs.node
 → /home/sbitdept/fennel/node_modules/libxmljs/build/Debug/xmljs.node
 → /home/sbitdept/fennel/node_modules/libxmljs/build/Release/xmljs.node
 → /home/sbitdept/fennel/node_modules/libxmljs/out/Debug/xmljs.node
 → /home/sbitdept/fennel/node_modules/libxmljs/Debug/xmljs.node
 → /home/sbitdept/fennel/node_modules/libxmljs/out/Release/xmljs.node
 → /home/sbitdept/fennel/node_modules/libxmljs/Release/xmljs.node
 → /home/sbitdept/fennel/node_modules/libxmljs/build/default/xmljs.node
 → /home/sbitdept/fennel/node_modules/libxmljs/compiled/4.3.2/linux/x64/xmljs.node
    at bindings (/home/sbitdept/fennel/node_modules/libxmljs/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/sbitdept/fennel/node_modules/libxmljs/lib/bindings.js:1:99)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/sbitdept/fennel/node_modules/libxmljs/index.js:4:16)
    at Module._compile (module.js:409:26)

====================================
 uname -a
Linux mail 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

 node -v
v4.3.2

npm -v
2.14.12

**Comment by sipgear** [comment]
update the node_module, the error got. thanks.
