### ISSUE TITLE
Create calendar fail with iCal

### ISSUE THREAD

**Issue by mdarveau** [LordEidi/fennel#11]
Hi,

I am getting the following error when creating a calendar with iCal:

```
Executing (ddaa0c4e-e3fc-4613-bf84-5a836c792a23): CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response "CALs", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_1f3c49c2d5e84c8788ec15877e3328a4$ BEGIN INSERT INTO "CALs" ("pkey","owner","timezone","order","free_busy_set","supported_cal_component","colour","displayname","synctoken","createdAt","updatedAt") VALUES ('DCA5F06A-B685-4A9C-9298-69C015542FA4','fennel','BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Apple Inc.//Mac OS X 10.11.5//EN
CALSCALE:GREGORIAN
BEGIN:VTIMEZONE
TZID:America/Montreal
BEGIN:DAYLIGHT
TZOFFSETFROM:-0500
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
DTSTART:20070311T020000
TZNAME:GMT-4
TZOFFSETTO:-0400
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0400
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
DTSTART:20071104T020000
TZNAME:GMT-5
TZOFFSETTO:-0500
END:STANDARD
END:VTIMEZONE
END:VCALENDAR
','239','YES','VEVENT','#44A703FF','Untitled',0,'2016-06-01 12:32:06.136 +00:00','2016-06-01 12:32:06.136 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_1f3c49c2d5e84c8788ec15877e3328a4$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();
Executing (ddaa0c4e-e3fc-4613-bf84-5a836c792a23): COMMIT;
Executing (default): SELECT "pkey", "owner", "timezone", "order", "free_busy_set", "supported_cal_component", "colour", "displayname", "synctoken", "createdAt", "updatedAt" FROM "CALs" AS "CAL" WHERE "CAL"."pkey" = 'DCA5F06A-B685-4A9C-9298-69C015542FA4';
Unhandled rejection SequelizeDatabaseError: value too long for type character varying(255)
    at Query.formatError (/Users/mdarveau/perso/workspace/fennel/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
    at null.<anonymous> (/Users/mdarveau/perso/workspace/fennel/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Query.handleError (/Users/mdarveau/perso/workspace/fennel/node_modules/pg/lib/query.js:108:8)
    at null.<anonymous> (/Users/mdarveau/perso/workspace/fennel/node_modules/pg/lib/client.js:171:26)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Socket.<anonymous> (/Users/mdarveau/perso/workspace/fennel/node_modules/pg/lib/connection.js:109:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

It looks like the value of the node ```calendar-timezone``` is
```
Child text: BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Apple Inc.//Mac OS X 10.11.5//EN
CALSCALE:GREGORIAN
BEGIN:VTIMEZONE
TZID:America/Montreal
BEGIN:DAYLIGHT
TZOFFSETFROM:-0500
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
DTSTART:20070311T020000
TZNAME:GMT-4
TZOFFSETTO:-0400
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0400
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
DTSTART:20071104T020000
TZNAME:GMT-5
TZOFFSETTO:-0500
END:STANDARD
END:VTIMEZONE
END:VCALENDAR
```

I have not checked the spec but I assume the client is or the the database model should be changed to Sequelize.TEXT?

I can make the PR.

**Comment by mdarveau** [comment]
Similar issue with ICs.content. It should be TEXT.

**Comment by LordEidi** [comment]
Thanks for that. I guess I found a third one while looking over your points. VCARD.content. Just pushed the correction.
