### ISSUE TITLE
crash on client connection

### ISSUE THREAD

**Issue by vitalyster** [LordEidi/fennel#6]
Got the following:

```
[2015-07-09 19:49:06.860] [DEBUG] fennelapp - Login process started for user: test
[2015-07-09 19:49:06.860] [DEBUG] fennelapp - Authenticating user with htaccess method.
[2015-07-09 19:49:06.867] [INFO] fennelapp - User logged in: test
[2015-07-09 19:49:06.867] [DEBUG] fennelapp - Method: PROPFIND, URL: /.well-known/carddav
[2015-07-09 19:49:06.869] [DEBUG] fennelapp - Called .well-known URL for carddav. Redirecting to /p/
[2015-07-09 19:49:07.031] [DEBUG] fennelapp - Login process started for user: test
[2015-07-09 19:49:07.032] [DEBUG] fennelapp - Authenticating user with htaccess method.
[2015-07-09 19:49:07.039] [INFO] fennelapp - User logged in: test
[2015-07-09 19:49:07.039] [DEBUG] fennelapp - Method: PROPFIND, URL: /p/
[2015-07-09 19:49:07.040] [DEBUG] fennelapp - principal.propfind called
[2015-07-09 19:49:07.042] [WARN] fennelapp - P-PF: not handled: resourcetype
[2015-07-09 19:49:07.216] [DEBUG] fennelapp - Login process started for user: test
[2015-07-09 19:49:07.217] [DEBUG] fennelapp - Authenticating user with htaccess method.
[2015-07-09 19:49:07.223] [INFO] fennelapp - User logged in: test
[2015-07-09 19:49:07.224] [DEBUG] fennelapp - Method: OPTIONS, URL: /p/test/
[2015-07-09 19:49:07.224] [DEBUG] fennelapp - principal.options called
[2015-07-09 19:49:11.891] [DEBUG] fennelapp - Login process started for user: test
[2015-07-09 19:49:11.892] [DEBUG] fennelapp - Authenticating user with htaccess method.
[2015-07-09 19:49:11.910] [INFO] fennelapp - User logged in: test
[2015-07-09 19:49:11.912] [DEBUG] fennelapp - Method: OPTIONS, URL: /p/test/
[2015-07-09 19:49:11.913] [DEBUG] fennelapp - principal.options called
[2015-07-09 19:49:12.025] [DEBUG] fennelapp - Login process started for user: test
[2015-07-09 19:49:12.026] [DEBUG] fennelapp - Authenticating user with htaccess method.
[2015-07-09 19:49:12.034] [INFO] fennelapp - User logged in: test
[2015-07-09 19:49:12.034] [DEBUG] fennelapp - Method: PROPFIND, URL: /p/test/
[2015-07-09 19:49:12.035] [DEBUG] fennelapp - principal.propfind called
[2015-07-09 19:49:13.401] [DEBUG] fennelapp - Login process started for user: test
[2015-07-09 19:49:13.402] [DEBUG] fennelapp - Authenticating user with htaccess method.
[2015-07-09 19:49:13.408] [INFO] fennelapp - User logged in: test
[2015-07-09 19:49:13.408] [DEBUG] fennelapp - Method: PROPFIND, URL: /card/test/
[2015-07-09 19:49:13.409] [DEBUG] fennelapp - addressbook.propfind called
/home/vt/fennel/node_modules/sequelize/lib/model.js:1608
    throw new Error(
          ^
Error: Missing where attribute in the options parameter passed to findOrCreate. Please note that the API has changed, and is now options only (an object with where, defaults keys, transaction etc.)
    at Model.findOrCreate (/home/vt/fennel/node_modules/sequelize/lib/model.js:1608:11)
    at Object.propfind (/home/vt/fennel/handler/addressbook.js:81:13)
    at Object.handleCard (/home/vt/fennel/libs/requesthandler.js:108:18)
    at IncomingMessage.<anonymous> (/home/vt/fennel/server.js:111:25)
    at IncomingMessage.emit (events.js:104:17)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

Account was added to iOS device using standard "Mail, Contacts, Calendars" settings

**Comment by vitalyster** [comment]
I've change sequelize package version to 1.7, all works now, contacts are synced well. Only one warning:
```
[2015-07-09 20:18:37.491] [WARN] fennelapp - CARD-PropFind: not handled: getctag
```

**Comment by LordEidi** [comment]
Yes, that is what I would have suggested.

Please note that the workaround in node.js regarding the MKCALENDAR verb in the CalDAV protocol does not work with current node.js versions anymore, see #5 for details. The node.js project fixed the original bug, so there is need for my fix anymore. But they did not release a version with that correction yet.

Which means either stay at the not so current node.js version or wait until there is a fixed version of node available.

I mention this because I tried to upgrade several libraries to the latest versions but hit my head on the above situation.

**Comment by LordEidi** [comment]
Does the crash still occur on the latest version?
